#!/usr/bin/env python3
"""
Extract Comparative Analysis from Model Comparison Report

This script parses a comparison_report.json file generated by compare_model_predictions.py
and extracts the GPT-4.1 comparative analysis for each gene pair. The analysis is formatted 
and printed to the console or saved to output files for easy reading.

Usage:
------
$ python extract_comparative_analysis.py [--input FILENAME] [--output-dir DIR] [--format {text,md,html}]

Arguments:
  --input FILENAME    Input JSON file (default: model_comparison_results.json)
  --output-dir DIR    Directory to save individual analysis files (default: analysis_outputs)
  --format FORMAT     Output format: text, md (markdown), or html (default: text)
  --single-file       Output all analyses to a single file instead of individual files
  --output-file FILE  Name of output file when using --single-file (default: all_comparative_analyses.{format})

Example:
--------
$ python extract_comparative_analysis.py --input comparison_report.json --format md
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Any, List


def format_text_output(analysis: str, gene_a: str, gene_b: str) -> str:
    """Format the analysis as plain text with clear section breaks."""
    header = f"COMPARATIVE ANALYSIS: {gene_a} - {gene_b}"
    separator = "=" * len(header)
    
    # Format the analysis text for readability
    # Add blank lines before section headers (1., 2., etc.)
    formatted_analysis = analysis
    for section in ["1.", "2.", "3.", "4."]:
        formatted_analysis = formatted_analysis.replace(f"{section}", f"\n{section}")
    
    output = f"{separator}\n{header}\n{separator}\n\n{formatted_analysis}\n\n"
    return output


def format_markdown_output(analysis: str, gene_a: str, gene_b: str) -> str:
    """Format the analysis as Markdown with proper heading structure."""
    # Replace section numbers with markdown headers
    formatted_analysis = analysis
    for i, section in enumerate(["1. Consensus", "2. Model Comparison", 
                               "3. Open Questions", "4. Reliability"], 1):
        pattern = f"{i}."
        if pattern in formatted_analysis:
            # Find the section title that follows the number
            parts = formatted_analysis.split(pattern, 1)
            if len(parts) > 1:
                section_content = parts[1]
                # Extract the title (everything before the first period or colon)
                title_end = min(
                    section_content.find(":") if section_content.find(":") != -1 else len(section_content),
                    section_content.find(".") if section_content.find(".") != -1 else len(section_content)
                )
                title = section_content[:title_end].strip() 
                # Replace with markdown header
                formatted_analysis = formatted_analysis.replace(
                    f"{pattern}{section_content[:title_end+1]}",
                    f"### {pattern} {title}\n"
                )
    
    # Add markdown formatting
    output = f"## Comparative Analysis: {gene_a} - {gene_b}\n\n{formatted_analysis}\n\n---\n\n"
    return output


def format_html_output(analysis: str, gene_a: str, gene_b: str) -> str:
    """Format the analysis as HTML with styled sections."""
    # Format the title and headers
    html_analysis = analysis.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    # Replace section numbers with HTML headers
    for i, section in enumerate(["1. Consensus", "2. Model Comparison", 
                               "3. Open Questions", "4. Reliability"], 1):
        pattern = f"{i}."
        if pattern in html_analysis:
            # Find the section title that follows the number
            parts = html_analysis.split(pattern, 1)
            if len(parts) > 1:
                section_content = parts[1]
                # Extract the title (everything before the first period or colon)
                title_end = min(
                    section_content.find(":") if section_content.find(":") != -1 else len(section_content),
                    section_content.find(".") if section_content.find(".") != -1 else len(section_content)
                )
                title = section_content[:title_end].strip()
                # Replace with HTML header
                html_analysis = html_analysis.replace(
                    f"{pattern}{section_content[:title_end+1]}",
                    f"<h3>{pattern} {title}</h3>"
                )
    
    # Convert newlines to <br> or <p> tags for better HTML rendering
    html_analysis = "<p>" + html_analysis.replace("\n\n", "</p><p>").replace("\n", "<br>") + "</p>"
    
    # Create full HTML
    output = f"""<div class="analysis">
    <h2>Comparative Analysis: {gene_a} - {gene_b}</h2>
    {html_analysis}
</div>
<hr>
"""
    return output


def extract_and_format_analyses(input_file: str, output_dir: str, format_type: str, 
                              single_file: bool, output_file: str) -> None:
    """
    Extract analyses from the comparison report and format them according to the specified format.
    """
    try:
        # Read the comparison report
        with open(input_file, 'r') as f:
            report = json.load(f)
        
        # Extract results
        results = report.get('results', [])
        if not results:
            print(f"Error: No results found in {input_file}")
            return
        
        analyses = []
        for result in results:
            # Skip entries with errors or missing data
            if 'error' in result or 'comparison' not in result:
                continue
                
            gene_a = result.get('gene_a', 'Unknown')
            gene_b = result.get('gene_b', 'Unknown')
            
            # Try to extract the GPT comparative analysis
            comparison = result.get('comparison', {})
            gpt_analysis = comparison.get('gpt_comparative_analysis', {})
            
            # The actual analysis text
            analysis_text = gpt_analysis.get('comparative_analysis', '')
            
            if not analysis_text:
                print(f"Warning: No comparative analysis found for {gene_a}-{gene_b}")
                continue
                
            # Format the analysis based on the requested format
            if format_type == 'text':
                formatted = format_text_output(analysis_text, gene_a, gene_b)
                file_ext = 'txt'
            elif format_type == 'md':
                formatted = format_markdown_output(analysis_text, gene_a, gene_b)
                file_ext = 'md'
            elif format_type == 'html':
                formatted = format_html_output(analysis_text, gene_a, gene_b)
                file_ext = 'html'
            else:
                print(f"Error: Unknown format type {format_type}")
                return
                
            # Save the analysis either to individual files or collect for a single file
            if not single_file:
                # Create output directory if it doesn't exist
                os.makedirs(output_dir, exist_ok=True)
                
                # Create a filename for this analysis
                filename = os.path.join(output_dir, f"analysis_{gene_a}_{gene_b}.{file_ext}")
                
                # Write to file
                with open(filename, 'w') as f:
                    f.write(formatted)
                print(f"Saved analysis for {gene_a}-{gene_b} to {filename}")
            else:
                analyses.append((gene_a, gene_b, formatted))
        
        # If we're collecting analyses for a single output file
        if single_file and analyses:
            # Create output directory if it doesn't exist
            if output_dir:
                os.makedirs(output_dir, exist_ok=True)
                full_path = os.path.join(output_dir, output_file)
            else:
                full_path = output_file
                
            # Create header content based on format
            if format_type == 'html':
                header = """<!DOCTYPE html>
<html>
<head>
    <title>Model Comparison Analyses</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }
        h1 { color: #2c3e50; }
        h2 { color: #3498db; margin-top: 30px; }
        h3 { color: #e74c3c; }
        .analysis { margin-bottom: 30px; }
        hr { border: 0; height: 1px; background: #eee; margin: 30px 0; }
    </style>
</head>
<body>
    <h1>Comparative Analyses of Gene Pair Interactions</h1>
"""
                footer = """</body>
</html>"""
            elif format_type == 'md':
                header = "# Comparative Analyses of Gene Pair Interactions\n\n"
                footer = ""
            else:  # text
                header = "COMPARATIVE ANALYSES OF GENE PAIR INTERACTIONS\n" + "=" * 40 + "\n\n"
                footer = ""
                
            # Write the combined file
            with open(full_path, 'w') as f:
                f.write(header)
                for gene_a, gene_b, content in analyses:
                    f.write(content)
                f.write(footer)
                
            print(f"Saved all analyses to {full_path}")
            
            # As a convenience, also print to console for text format
            if format_type == 'text' and len(analyses) <= 3:  # Only for a reasonable number
                for gene_a, gene_b, content in analyses:
                    print(content)
            
    except Exception as e:
        print(f"Error processing file: {e}")
        import traceback
        traceback.print_exc()


def main():
    # Define command-line arguments
    parser = argparse.ArgumentParser(
        description="Extract and format comparative analyses from model comparison reports."
    )
    parser.add_argument(
        "--input", default="model_comparison_results.json",
        help="Input JSON file from compare_model_predictions.py (default: model_comparison_results.json)"
    )
    parser.add_argument(
        "--output-dir", default="analysis_outputs",
        help="Directory to save formatted analysis files (default: analysis_outputs)"
    )
    parser.add_argument(
        "--format", choices=["text", "md", "html"], default="text",
        help="Output format: text, md (markdown), or html (default: text)"
    )
    parser.add_argument(
        "--single-file", action="store_true",
        help="Output all analyses to a single file instead of individual files"
    )
    parser.add_argument(
        "--output-file", 
        help="Name of the output file when using --single-file (default: generated based on format)"
    )
    
    # Parse the arguments
    args = parser.parse_args()
    
    # Validate the input file
    if not os.path.exists(args.input):
        print(f"Error: Input file {args.input} not found")
        sys.exit(1)
    
    # Generate default output filename if not provided
    if args.single_file and not args.output_file:
        if args.format == "text":
            args.output_file = "all_comparative_analyses.txt"
        elif args.format == "md":
            args.output_file = "all_comparative_analyses.md"
        elif args.format == "html":
            args.output_file = "all_comparative_analyses.html"
    
    # Process the file
    extract_and_format_analyses(
        args.input, 
        args.output_dir,
        args.format,
        args.single_file,
        args.output_file
    )


if __name__ == "__main__":
    main()